const countries = {
    "ilo-PH": "Ilocano",
    "bcl-PH": "Bicol",
    "ceb-PH": "Cebuano",
    "hil-PH": "Hiligaynon",
    "war-PH": "Waray",
    "ar-SA": "Arabic",
    "de-DE": "German",
    "en-GB": "English",
    "es-ES": "Spanish",
    "fr-FR": "French",
    "hi-IN": "Hindi",
    "id-ID": "Indonesian",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "pa-IN": "Panjabi",
    "th-TH": "Thai",
    "tl-PH": "Tagalog",
    "vi-VN": "Vietnamese",
}
